defaults: &defaults
  aws_region: us-east-1
  domain_name: lenfree-example.com
  environment: production
  environment_short: pr
  prefix: management
  availability_zones:
    - 'us-east-1a'
    - 'us-east-1b'
    - 'us-east-1e'

vpc:
  << : *defaults 
  source: './modules/management_vpc'
  s3_bucket_terraform: terraform-management-prod
  s3_bucket_versioning: false
  s3_bucket_acl: authenticated-read
  vpc_cidr: 10.61.64.0/22
  vpc_tag_name: mgmt_vpc
  public_subnets:
    - 10.61.64.64/26
    - 10.61.65.64/26
    - 10.61.66.64/26
  private_subnets:
    - 10.61.64.0/26
    - 10.61.65.0/26
    - 10.61.66.0/26

http_server:
  << : *defaults 
  source: './modules/web_server'
  key_name: mykey # AWS Key Pair
  ami: ami-408c7f28
  s3_bucket_acl: authenticated-read
  vpc_id: "${module.vpc.id}"
  http_port: 8080
  instance_type: t1.micro
  public_subnet_ids: "${module.vpc.public_subnet_ids}"
  route53_zone: "${module.vpc.zone_id}"
  route53_record_name: www
  route53_record_type: A

elasticsearch:
  << : *defaults
  source: './modules/elasticsearch'
  elasticsearch_domain_name: 'myes'
  elasticsearch_version: 2.3
  allow_explicit_index: 'true'
  allow_source_cidrs: 0.0.0.0/0
  automated_snapshot_start_hour: 23
  instance_type: m3.large.elasticsearch
  instance_count: 1
  dedicated_master_enabled: true
  dedicated_master_type: t2.small.elasticsearch
  dedicated_master_count: 2
  zone_awareness_enabled: false
  route53_zone: "${module.vpc.zone_id}"
  route53_record_name: mykibana
  route53_record_type: CNAME

cloudtrail:
  << : *defaults
  source: './modules/cloudtrail'

logstash_es:
  << : *defaults
  source: './modules/logstash_es'
  key_name: mykey # AWS Key Pair
  ami: ami-408c7f28
  vpc_id: "${module.vpc.id}"
  # This instance needs more memory to avoid getting error with
  # logstash-core-event-java Logstash plugin
  instance_type: m3.medium
  # Temporarily assign public subnet for troubleshooting.
  private_subnet_ids: "${module.vpc.public_subnet_ids}"
  elasticsearch_endpoint: "${module.elasticsearch.endpoint}"
  cloudtrail_s3_bucket_arn: "${module.cloudtrail.arn}"
  elasticsearch_arn: "${module.elasticsearch.arn}"

